"""
unipmx — Polymarket / prediction market toolkit.

Architecture: Events/ Historical/ Users/ Feed/ Display/ Plots/
"""

from unipmx.Display import display
from unipmx.Plots import plotChart
from unipmx.clients import All, Kalshi, Limitless, Myriad, Polymarket, Probable, Smarkets
from unipmx.Events import (
    fetchEvent,
    fetchEvents,
    fetchMarket,
    fetchMarkets,
    fetchOrderBook,
    fetchOrderBookByQuery,
)
from unipmx.Feed import (
    firehose,
    unwatchAddress,
    unwatchOrderBook,
    watchAddress,
    watchAllOrderBooks,
    watchOrderBook,
    watchOrderBooks,
    watchPrices,
    watchTrades,
    watchUserPositions,
    watchUserTransactions,
)
from unipmx.Historical import (
    fetchHistorical,
    fetchHistoricalEventPrice,
    fetchHistoricalMarketOpenInterest,
    fetchHistoricalMarketPrice,
    fetchHistoricalMarketPriceOhlcv,
    fetchHistoricalMarketTrades,
    fetchHistoricalMarketVolume,
    fetchHistoricalUserPnl,
    fetchHistoricalUserTradeHistory,
    fetchHistoricalUserWalletConnections,
    fetchOhlcv,
    fetchTrades,
)
from unipmx.Platform import (
    fetchPlatformCategories,
    fetchPlatformFees,
    fetchPlatformStats,
    fetchPlatformStatus,
    fetchPlatformVenues,
)
from unipmx.Users import (
    fetchUserActivity,
    fetchUserBalance,
    fetchUserFollowers,
    fetchUserFollowing,
    fetchUserMarkets,
    fetchUserPnL,
    fetchUserPortfolioValue,
    fetchUserPositions,
    fetchUserProfile,
    fetchUserRank,
    fetchUserTrades,
    fetchUserWalletAge,
    fetchUserWalletConnections,
    fetchUsersLeaderboard,
    findUserStyle,
)
from unipmx.client import getClient

__all__ = [
    "All",
    "Kalshi",
    "Limitless",
    "Myriad",
    "Polymarket",
    "Probable",
    "Smarkets",
    "display",
    "plotChart",
    "fetchPlatformCategories",
    "fetchPlatformFees",
    "fetchPlatformStats",
    "fetchPlatformStatus",
    "fetchPlatformVenues",
    "fetchEvent",
    "fetchEvents",
    "fetchMarket",
    "fetchMarkets",
    "fetchHistorical",
    "fetchHistoricalEventPrice",
    "fetchHistoricalMarketOpenInterest",
    "fetchHistoricalMarketPrice",
    "fetchHistoricalMarketPriceOhlcv",
    "fetchHistoricalMarketTrades",
    "fetchHistoricalMarketVolume",
    "fetchHistoricalUserPnl",
    "fetchHistoricalUserTradeHistory",
    "fetchHistoricalUserWalletConnections",
    "fetchOhlcv",
    "fetchOrderBook",
    "fetchOrderBookByQuery",
    "fetchTrades",
    "fetchUserActivity",
    "fetchUserBalance",
    "fetchUserFollowers",
    "fetchUserFollowing",
    "fetchUserMarkets",
    "fetchUserPnL",
    "fetchUserPortfolioValue",
    "fetchUserPositions",
    "fetchUserProfile",
    "fetchUserRank",
    "fetchUserTrades",
    "fetchUserWalletAge",
    "fetchUserWalletConnections",
    "fetchUsersLeaderboard",
    "findUserStyle",
    "getClient",
    "firehose",
    "unwatchAddress",
    "unwatchOrderBook",
    "watchAddress",
    "watchAllOrderBooks",
    "watchOrderBook",
    "watchOrderBooks",
    "watchPrices",
    "watchTrades",
    "watchUserPositions",
    "watchUserTransactions",
]
